#!/bin/sh
set -eux

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 FOLDER_ID" >&2
  exit 1
fi
FOLDER_ID=${1}

find ./ -iname "*.md" -type f -exec sh -c 'pandoc "${0}" -o "${0%.md}.docx"' {} \;
find ./ -iname "*.md" -type f -exec sh -c 'rm ${0}' {} \;

gdrive --service-account credentials.json sync upload ./ ${FOLDER_ID}