version: 2.1
orbs:
  docker: circleci/docker@0.5.18

workflows:
  publish:
    jobs:
      - docker/hadolint:
          ignore-rules: 'DL3008'
      - docker/publish:
          image: matsuri/$CIRCLE_PROJECT_REPONAME
          registry: quay.io
          lint-dockerfile: true
          tag: '${CIRCLE_TAG//v}, latest'
          use-remote-docker: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
